import { ILoader } from '../type/ILoader';
import { IProduct } from '../type/productList';

export class Loader implements ILoader {
    getProducts(): Array<IProduct> {
        return [
            {
                name: 'Apple iphone 11',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 20,
                startYear: 2020,
                maker: 'apple',
                color: 'green',
                camQuant: '2',
                popular: true,
            },
            {
                name: 'Apple iphone 4',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 4,
                startYear: 2004,
                maker: 'apple',
                color: 'red',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Samsung',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 1,
                startYear: 2021,
                maker: 'samsung',
                color: 'red',
                camQuant: '1',
                popular: true,
            },
            {
                name: 'Samsung S3',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 1,
                startYear: 2008,
                maker: 'samsung',
                color: 'red',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Xiaomi',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 8,
                startYear: 2019,
                maker: 'xiaomi',
                color: 'black',
                camQuant: '3',
                popular: true,
            },
            {
                name: 'Xiaomi MI9',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 3,
                startYear: 2017,
                maker: 'xiaomi',
                color: 'red',
                camQuant: '3',
                popular: false,
            },
            {
                name: 'Apple iphone 12',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 7,
                startYear: 2010,
                maker: 'apple',
                color: 'black',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Xiaomi 990',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 8,
                startYear: 2009,
                maker: 'xiaomi',
                color: 'red',
                camQuant: '2',
                popular: true,
            },
            {
                name: 'Xiaomi 9',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 3,
                startYear: 2013,
                maker: 'xiaomi',
                color: 'green',
                camQuant: '3',
                popular: true,
            },
            {
                name: 'Apple iphone 12',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 7,
                startYear: 2010,
                maker: 'apple',
                color: 'black',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Apple iphone 11',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 6,
                startYear: 2000,
                maker: 'apple',
                color: 'red',
                camQuant: '1',
                popular: true,
            },
            {
                name: 'Apple iphone 11',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 5,
                startYear: 2015,
                maker: 'apple',
                color: 'black',
                camQuant: '3',
                popular: false,
            },
            {
                name: 'Apple iphone 11',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 20,
                startYear: 2020,
                maker: 'apple',
                color: 'green',
                camQuant: '2',
                popular: true,
            },
            {
                name: 'Apple iphone 4',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 4,
                startYear: 2004,
                maker: 'apple',
                color: 'red',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Samsung',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 1,
                startYear: 2021,
                maker: 'samsung',
                color: 'red',
                camQuant: '1',
                popular: true,
            },
            {
                name: 'Samsung S3',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 1,
                startYear: 2008,
                maker: 'samsung',
                color: 'red',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Xiaomi',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 8,
                startYear: 2019,
                maker: 'xiaomi',
                color: 'black',
                camQuant: '3',
                popular: true,
            },
            {
                name: 'Xiaomi MI9',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 8,
                startYear: 2017,
                maker: 'xiaomi',
                color: 'red',
                camQuant: '3',
                popular: false,
            },
            {
                name: 'Apple iphone 12',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 7,
                startYear: 2010,
                maker: 'apple',
                color: 'black',
                camQuant: '1',
                popular: false,
            },
            {
                name: 'Apple iphone 111',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 9,
                startYear: 2000,
                maker: 'apple',
                color: 'red',
                camQuant: '1',
                popular: true,
            },
            {
                name: 'Apple iphone 23',
                urlImg: './src/img/product/apple_iphone_11_pro.jpg',
                quantity: 2,
                startYear: 2011,
                maker: 'apple',
                color: 'black',
                camQuant: '1',
                popular: false,
            },
        ];
    }
}
